import { Action, UserActionTypes } from './types';
import { Auth } from '../../pages/authentication/components/auth-form/types';
import { Registration } from '../../pages/registration/components/registration-form/types';
import { UserSuccessActionProperty } from '../reducers/types';
declare const registerUserRequest: (registerUserData: Registration) => Action;
declare const registerUserSuccess: () => Action;
declare const registerUserFailure: (err: Error) => Action;
declare const registerClearStatus: () => Action;
declare const authorizeUserRequest: (authData: Auth) => Action;
declare const authorizeUserSuccsess: (user: UserSuccessActionProperty) => Action;
declare const authorizeUserFailure: (error: Error) => Action;
declare const unauthorizeRequest: () => Action;
declare const unauthorizeSuccess: () => Action;
declare const unauthorizeFailure: (err: Error) => Action;
export { UserActionTypes, registerUserRequest, registerUserSuccess, registerUserFailure, registerClearStatus, authorizeUserRequest, authorizeUserSuccsess, authorizeUserFailure, unauthorizeRequest, unauthorizeSuccess, unauthorizeFailure, };
